import { Timestamp } from 'firebase/firestore';
import type {
  EnhancedCarePlan,
  NursingTask,
  FeedingTaskDetails,
  MedicationTaskDetails,
  VitalSignsTaskDetails,
  ProcedureTaskDetails,
} from '../types/tasks';
import type { MedicationPrescription } from '../types';

/**
 * Generates feeding tasks from a care plan
 * @param carePlan The enhanced care plan with feeding schedule
 * @param startTime Starting timestamp for task generation
 * @param durationHours How many hours ahead to generate tasks
 * @returns Array of nursing tasks for feeding
 */
export function generateFeedingTasks(
  carePlan: EnhancedCarePlan,
  startTime: Timestamp,
  durationHours: number = 24
): NursingTask[] {
  if (!carePlan.feedingPlan) return [];

  const tasks: NursingTask[] = [];
  const { frequency, volumePerFeed, feedType, route, fortification, aspirateBeforeFeed } = carePlan.feedingPlan;

  const startMillis = startTime.toMillis();
  const endMillis = startMillis + durationHours * 60 * 60 * 1000;

  let currentTime = startMillis;
  let instanceNumber = 1;
  const seriesId = `feed-series-${carePlan.id}-${Date.now()}`;

  while (currentTime < endMillis) {
    const scheduledDateTime = Timestamp.fromMillis(currentTime);
    const timeOfDay = new Date(currentTime).toTimeString().slice(0, 5); // "HH:mm"

    const feedingDetails: FeedingTaskDetails = {
      volumeML: volumePerFeed,
      feedType,
      route,
      aspirateRequired: aspirateBeforeFeed,
      fortification: fortification?.type,
      medicationsToInclude: [], // Will be populated when linking medications
    };

    const task: NursingTask = {
      id: `task-feed-${carePlan.babyId}-${currentTime}`,
      babyId: carePlan.babyId,
      generatedFrom: {
        sourceType: 'care_plan',
        sourceId: carePlan.id,
        version: carePlan.version,
      },
      taskType: 'feeding',
      taskCategory: 'routine',
      scheduledDateTime,
      scheduledTimeOfDay: timeOfDay,
      recurrencePattern: {
        frequency: `${frequency}-hourly` as any,
        seriesId,
        instanceNumber,
      },
      taskDetails: feedingDetails,
      status: 'pending',
      priority: 'routine',
      autoGenerated: true,
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
    };

    tasks.push(task);

    currentTime += frequency * 60 * 60 * 1000; // Add frequency in milliseconds
    instanceNumber++;
  }

  return tasks;
}

/**
 * Generates medication tasks from prescriptions
 * @param prescriptions Array of active medication prescriptions
 * @param startTime Starting timestamp for task generation
 * @param durationHours How many hours ahead to generate tasks
 * @returns Array of nursing tasks for medication administration
 */
export function generateMedicationTasks(
  prescriptions: MedicationPrescription[],
  startTime: Timestamp,
  durationHours: number = 24
): NursingTask[] {
  const tasks: NursingTask[] = [];

  prescriptions.forEach((prescription) => {
    if (prescription.status !== 'approved') return;

    const startMillis = startTime.toMillis();
    const endMillis = startMillis + durationHours * 60 * 60 * 1000;

    prescription.timings.forEach((timingString) => {
      // Parse time string like "08:00"
      const [hours, minutes] = timingString.split(':').map(Number);

      // Find next occurrence of this time
      let scheduledDate = new Date(startMillis);
      scheduledDate.setHours(hours, minutes, 0, 0);

      // If time has passed today, start from tomorrow
      if (scheduledDate.getTime() < startMillis) {
        scheduledDate.setDate(scheduledDate.getDate() + 1);
      }

      // Generate tasks for each day within duration
      while (scheduledDate.getTime() < endMillis) {
        const scheduledDateTime = Timestamp.fromMillis(scheduledDate.getTime());

        const medDetails: MedicationTaskDetails = {
          prescriptionId: prescription.id,
          medicationName: prescription.medicationName,
          dose: prescription.dose,
          route: prescription.route,
          canBeGivenInFeed: prescription.canBeGivenInFeed || false,
          mustBeGivenSeparately: !prescription.canBeGivenInFeed,
        };

        const task: NursingTask = {
          id: `task-med-${prescription.id}-${scheduledDate.getTime()}`,
          babyId: prescription.babyId,
          generatedFrom: {
            sourceType: 'medication_prescription',
            sourceId: prescription.id,
          },
          taskType: 'medication',
          taskCategory: prescription.isPRN ? 'prn' : 'routine',
          scheduledDateTime,
          scheduledTimeOfDay: timingString,
          taskDetails: medDetails,
          status: 'pending',
          priority: 'important',
          flags: prescription.controlledDrug ? ['needs_two_nurses'] : undefined,
          autoGenerated: true,
          createdAt: Timestamp.now(),
          updatedAt: Timestamp.now(),
        };

        tasks.push(task);

        scheduledDate.setDate(scheduledDate.getDate() + 1); // Next day
      }
    });
  });

  return tasks;
}

/**
 * Generates vital signs observation tasks from care plan
 * @param carePlan The enhanced care plan with observation schedule
 * @param startTime Starting timestamp for task generation
 * @param durationHours How many hours ahead to generate tasks
 * @returns Array of nursing tasks for vital signs
 */
export function generateVitalSignsTasks(
  carePlan: EnhancedCarePlan,
  startTime: Timestamp,
  durationHours: number = 24
): NursingTask[] {
  if (!carePlan.observationPlan || carePlan.observationPlan.frequency === 'continuous') return [];

  const tasks: NursingTask[] = [];
  const { frequency, parameters } = carePlan.observationPlan;

  // Map frequency to hours
  const frequencyHours: { [key: string]: number } = {
    hourly: 1,
    '2-hourly': 2,
    '4-hourly': 4,
    '6-hourly': 6,
  };

  const intervalHours = frequencyHours[frequency];
  if (!intervalHours) return [];

  const startMillis = startTime.toMillis();
  const endMillis = startMillis + durationHours * 60 * 60 * 1000;

  let currentTime = startMillis;
  let instanceNumber = 1;
  const seriesId = `vitals-series-${carePlan.id}-${Date.now()}`;

  // Collect parameters to monitor
  const parametersToMonitor: ('temperature' | 'heartRate' | 'respiratoryRate' | 'oxygenSaturation' | 'bloodPressure')[] = [];
  if (parameters.temperature) parametersToMonitor.push('temperature');
  if (parameters.heartRate) parametersToMonitor.push('heartRate');
  if (parameters.respiratoryRate) parametersToMonitor.push('respiratoryRate');
  if (parameters.oxygenSaturation) parametersToMonitor.push('oxygenSaturation');
  if (parameters.bloodPressure) parametersToMonitor.push('bloodPressure');

  while (currentTime < endMillis) {
    const scheduledDateTime = Timestamp.fromMillis(currentTime);
    const timeOfDay = new Date(currentTime).toTimeString().slice(0, 5);

    const vitalSignsDetails: VitalSignsTaskDetails = {
      parameters: parametersToMonitor,
      isRoutineCheck: true,
    };

    const task: NursingTask = {
      id: `task-vitals-${carePlan.babyId}-${currentTime}`,
      babyId: carePlan.babyId,
      generatedFrom: {
        sourceType: 'care_plan',
        sourceId: carePlan.id,
        version: carePlan.version,
      },
      taskType: 'vital_signs',
      taskCategory: 'routine',
      scheduledDateTime,
      scheduledTimeOfDay: timeOfDay,
      recurrencePattern: {
        frequency: frequency as any,
        seriesId,
        instanceNumber,
      },
      taskDetails: vitalSignsDetails,
      status: 'pending',
      priority: 'routine',
      autoGenerated: true,
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
    };

    tasks.push(task);

    currentTime += intervalHours * 60 * 60 * 1000;
    instanceNumber++;
  }

  return tasks;
}

/**
 * Generates procedure tasks from care plan
 * @param carePlan The enhanced care plan with procedural schedule
 * @param startTime Starting timestamp for task generation
 * @param durationHours How many hours ahead to generate tasks
 * @returns Array of nursing tasks for procedures
 */
export function generateProcedureTasks(
  carePlan: EnhancedCarePlan,
  startTime: Timestamp,
  durationHours: number = 24
): NursingTask[] {
  if (!carePlan.proceduralPlan) return [];

  const tasks: NursingTask[] = [];
  const { lineCare, tubeCare, positionChanges, skinAssessments } = carePlan.proceduralPlan;

  const startMillis = startTime.toMillis();
  const endMillis = startMillis + durationHours * 60 * 60 * 1000;

  // Line flushes
  if (lineCare && lineCare.lineIds.length > 0) {
    lineCare.lineIds.forEach((lineId) => {
      let currentTime = startMillis;
      let instanceNumber = 1;

      while (currentTime < endMillis) {
        const scheduledDateTime = Timestamp.fromMillis(currentTime);
        const timeOfDay = new Date(currentTime).toTimeString().slice(0, 5);

        const procedureDetails: ProcedureTaskDetails = {
          procedureType: 'line_flush',
          targetLineOrTubeId: lineId,
          specificInstructions: 'Flush with normal saline per protocol',
        };

        const task: NursingTask = {
          id: `task-line-flush-${lineId}-${currentTime}`,
          babyId: carePlan.babyId,
          generatedFrom: {
            sourceType: 'care_plan',
            sourceId: carePlan.id,
            version: carePlan.version,
          },
          taskType: 'line_care',
          taskCategory: 'routine',
          scheduledDateTime,
          scheduledTimeOfDay: timeOfDay,
          taskDetails: procedureDetails,
          status: 'pending',
          priority: 'important',
          autoGenerated: true,
          createdAt: Timestamp.now(),
          updatedAt: Timestamp.now(),
        };

        tasks.push(task);

        currentTime += lineCare.flushFrequency * 60 * 60 * 1000;
        instanceNumber++;
      }
    });
  }

  // Tube position checks
  if (tubeCare && tubeCare.tubeIds.length > 0) {
    tubeCare.tubeIds.forEach((tubeId) => {
      let currentTime = startMillis;

      while (currentTime < endMillis) {
        const scheduledDateTime = Timestamp.fromMillis(currentTime);
        const timeOfDay = new Date(currentTime).toTimeString().slice(0, 5);

        const procedureDetails: ProcedureTaskDetails = {
          procedureType: 'tube_position_check',
          targetLineOrTubeId: tubeId,
          specificInstructions: 'Check pH and external length',
        };

        const task: NursingTask = {
          id: `task-tube-check-${tubeId}-${currentTime}`,
          babyId: carePlan.babyId,
          generatedFrom: {
            sourceType: 'care_plan',
            sourceId: carePlan.id,
            version: carePlan.version,
          },
          taskType: 'procedure',
          taskCategory: 'routine',
          scheduledDateTime,
          scheduledTimeOfDay: timeOfDay,
          taskDetails: procedureDetails,
          status: 'pending',
          priority: 'important',
          autoGenerated: true,
          createdAt: Timestamp.now(),
          updatedAt: Timestamp.now(),
        };

        tasks.push(task);

        currentTime += tubeCare.positionCheckFrequency * 60 * 60 * 1000;
      }
    });
  }

  // Position changes
  if (positionChanges) {
    let currentTime = startMillis;
    let positionIndex = 0;

    while (currentTime < endMillis) {
      const scheduledDateTime = Timestamp.fromMillis(currentTime);
      const timeOfDay = new Date(currentTime).toTimeString().slice(0, 5);

      const position = positionChanges.positions[positionIndex % positionChanges.positions.length];

      const procedureDetails: ProcedureTaskDetails = {
        procedureType: 'position_change',
        specificInstructions: `Change to ${position} position`,
      };

      const task: NursingTask = {
        id: `task-position-${carePlan.babyId}-${currentTime}`,
        babyId: carePlan.babyId,
        generatedFrom: {
          sourceType: 'care_plan',
          sourceId: carePlan.id,
          version: carePlan.version,
        },
        taskType: 'position_change',
        taskCategory: 'routine',
        scheduledDateTime,
        scheduledTimeOfDay: timeOfDay,
        taskDetails: procedureDetails,
        status: 'pending',
        priority: 'routine',
        autoGenerated: true,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
      };

      tasks.push(task);

      currentTime += positionChanges.frequency * 60 * 60 * 1000;
      positionIndex++;
    }
  }

  // Skin assessments
  if (skinAssessments) {
    let currentTime = startMillis;

    while (currentTime < endMillis) {
      const scheduledDateTime = Timestamp.fromMillis(currentTime);
      const timeOfDay = new Date(currentTime).toTimeString().slice(0, 5);

      const procedureDetails: ProcedureTaskDetails = {
        procedureType: 'skin_assessment',
        specificInstructions: 'Check for pressure areas and skin integrity',
      };

      const task: NursingTask = {
        id: `task-skin-${carePlan.babyId}-${currentTime}`,
        babyId: carePlan.babyId,
        generatedFrom: {
          sourceType: 'care_plan',
          sourceId: carePlan.id,
          version: carePlan.version,
        },
        taskType: 'skin_care',
        taskCategory: 'routine',
        scheduledDateTime,
        scheduledTimeOfDay: timeOfDay,
        taskDetails: procedureDetails,
        status: 'pending',
        priority: 'routine',
        autoGenerated: true,
        createdAt: Timestamp.now(),
        updatedAt: Timestamp.now(),
      };

      tasks.push(task);

      currentTime += skinAssessments.frequency * 60 * 60 * 1000;
    }
  }

  return tasks;
}

/**
 * Generates all tasks from a care plan
 * @param carePlan The enhanced care plan
 * @param prescriptions Associated medication prescriptions
 * @param startTime Starting timestamp
 * @param durationHours How many hours ahead to generate
 * @returns Combined array of all nursing tasks
 */
export function generateAllTasks(
  carePlan: EnhancedCarePlan,
  prescriptions: MedicationPrescription[],
  startTime: Timestamp,
  durationHours: number = 24
): NursingTask[] {
  const feedingTasks = generateFeedingTasks(carePlan, startTime, durationHours);
  const medicationTasks = generateMedicationTasks(
    prescriptions.filter((p) => p.babyId === carePlan.babyId),
    startTime,
    durationHours
  );
  const vitalSignsTasks = generateVitalSignsTasks(carePlan, startTime, durationHours);
  const procedureTasks = generateProcedureTasks(carePlan, startTime, durationHours);

  return [...feedingTasks, ...medicationTasks, ...vitalSignsTasks, ...procedureTasks].sort(
    (a, b) => a.scheduledDateTime.toMillis() - b.scheduledDateTime.toMillis()
  );
}
