import { Timestamp } from 'firebase/firestore';
import type { Baby, User, MedicationPrescription, MedicationAdministration, FeedingRecord, CarePlan, VitalSign } from '../types';
import { ROLE_PERMISSIONS } from '../types';

// Helper to create timestamps
const now = () => Timestamp.now();
const daysAgo = (days: number) => Timestamp.fromDate(new Date(Date.now() - days * 24 * 60 * 60 * 1000));
const hoursAgo = (hours: number) => Timestamp.fromDate(new Date(Date.now() - hours * 60 * 60 * 1000));

// Demo Users
export const DEMO_USERS: User[] = [
  {
    id: 'sarah-nurse',
    email: 'sarah.nurse@demo.nicu',
    firstName: 'Sarah',
    lastName: 'Johnson',
    role: 'bedside_nurse',
    permissions: ROLE_PERMISSIONS.bedside_nurse,
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'emma-consultant',
    email: 'emma.consultant@demo.nicu',
    firstName: 'Dr. Emma',
    lastName: 'Williams',
    role: 'consultant',
    permissions: ROLE_PERMISSIONS.consultant,
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'james-doctor',
    email: 'james.doctor@demo.nicu',
    firstName: 'Dr. James',
    lastName: 'Chen',
    role: 'junior_doctor',
    permissions: ROLE_PERMISSIONS.junior_doctor,
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'maria-manager',
    email: 'maria.manager@demo.nicu',
    firstName: 'Maria',
    lastName: 'Garcia',
    role: 'ward_manager',
    permissions: ROLE_PERMISSIONS.ward_manager,
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'tom-physio',
    email: 'tom.physio@demo.nicu',
    firstName: 'Tom',
    lastName: 'Andrews',
    role: 'physiotherapist',
    permissions: ROLE_PERMISSIONS.physiotherapist,
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'rachel-parent',
    email: 'rachel.parent@demo.nicu',
    firstName: 'Rachel',
    lastName: 'Smith',
    role: 'parent',
    permissions: ROLE_PERMISSIONS.parent,
    babyIds: ['daisy'],
    createdAt: now(),
    updatedAt: now(),
  },
];

// Demo Babies
export const DEMO_BABIES: Baby[] = [
  {
    id: 'daisy',
    hospitalNumber: 'NH001234',
    firstName: 'Daisy',
    lastName: 'Smith',
    dateOfBirth: daysAgo(5),
    gestationalAgeAtBirth: { weeks: 32, days: 4 },
    birthWeight: 1850,
    sex: 'female',
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    bedNumber: 'Room 1',
    admissionDate: daysAgo(5),
    diagnoses: ['Prematurity', 'Respiratory distress syndrome'],
    parentUserIds: ['rachel-parent'],
    primaryNurseId: 'sarah-nurse',
    consultantId: 'emma-consultant',
    isActive: true,
    createdAt: daysAgo(5),
    updatedAt: now(),
    createdBy: 'system',
  },
  {
    id: 'elsa',
    hospitalNumber: 'NH001235',
    firstName: 'Elsa',
    lastName: 'Brown',
    dateOfBirth: daysAgo(12),
    gestationalAgeAtBirth: { weeks: 28, days: 2 },
    birthWeight: 1120,
    sex: 'female',
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    bedNumber: 'Room 2',
    admissionDate: daysAgo(12),
    diagnoses: ['Extreme prematurity', 'Bronchopulmonary dysplasia', 'Patent ductus arteriosus'],
    parentUserIds: [],
    primaryNurseId: 'sarah-nurse',
    consultantId: 'emma-consultant',
    isActive: true,
    createdAt: daysAgo(12),
    updatedAt: now(),
    createdBy: 'system',
  },
];

// Medication Prescriptions
export const DEMO_PRESCRIPTIONS: MedicationPrescription[] = [
  {
    id: 'rx-daisy-caffeine',
    babyId: 'daisy',
    medicationName: 'Caffeine Citrate',
    dose: { amount: 5, unit: 'mg/kg' },
    route: 'oral',
    frequency: 'OD',
    timings: ['08:00'],
    startDate: daysAgo(5),
    indication: 'Apnoea of prematurity',
    canBeGivenInFeed: true,
    mustBeGivenSeparately: false,
    status: 'approved',
    prescribedBy: 'emma-consultant',
    prescribedAt: daysAgo(5),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'rx-daisy-vitamin-d',
    babyId: 'daisy',
    medicationName: 'Vitamin D',
    dose: { amount: 400, unit: 'units' },
    route: 'oral',
    frequency: 'OD',
    timings: ['08:00'],
    startDate: daysAgo(5),
    indication: 'Prematurity supplementation',
    canBeGivenInFeed: true,
    mustBeGivenSeparately: false,
    status: 'approved',
    prescribedBy: 'emma-consultant',
    prescribedAt: daysAgo(5),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'rx-elsa-caffeine',
    babyId: 'elsa',
    medicationName: 'Caffeine Citrate',
    dose: { amount: 5, unit: 'mg/kg' },
    route: 'oral',
    frequency: 'OD',
    timings: ['08:00'],
    startDate: daysAgo(12),
    indication: 'Apnoea of prematurity',
    canBeGivenInFeed: true,
    mustBeGivenSeparately: false,
    status: 'approved',
    prescribedBy: 'emma-consultant',
    prescribedAt: daysAgo(12),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
  {
    id: 'rx-elsa-dexamethasone',
    babyId: 'elsa',
    medicationName: 'Dexamethasone',
    dose: { amount: 0.15, unit: 'mg/kg' },
    route: 'IV',
    frequency: 'BD',
    timings: ['08:00', '20:00'],
    startDate: daysAgo(10),
    indication: 'Bronchopulmonary dysplasia',
    canBeGivenInFeed: false,
    mustBeGivenSeparately: true,
    status: 'approved',
    prescribedBy: 'emma-consultant',
    prescribedAt: daysAgo(10),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: 'rx-elsa-vitamin-d',
    babyId: 'elsa',
    medicationName: 'Vitamin D',
    dose: { amount: 400, unit: 'units' },
    route: 'oral',
    frequency: 'OD',
    timings: ['08:00'],
    startDate: daysAgo(12),
    indication: 'Prematurity supplementation',
    canBeGivenInFeed: true,
    mustBeGivenSeparately: false,
    status: 'approved',
    prescribedBy: 'emma-consultant',
    prescribedAt: daysAgo(12),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
];

// Medication Administrations (for today)
const today8am = new Date();
today8am.setHours(8, 0, 0, 0);
const today2pm = new Date();
today2pm.setHours(14, 0, 0, 0);
const today8pm = new Date();
today8pm.setHours(20, 0, 0, 0);

export let DEMO_MEDICATIONS: MedicationAdministration[] = [
  // Daisy - 08:00 medications (pending)
  {
    id: 'med-daisy-caffeine-today',
    babyId: 'daisy',
    prescriptionId: 'rx-daisy-caffeine',
    medicationName: 'Caffeine Citrate',
    dose: { amount: 5, unit: 'mg/kg' },
    route: 'oral',
    scheduledTime: Timestamp.fromDate(today8am),
    administrationMethod: 'in_feed',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'med-daisy-vitamin-d-today',
    babyId: 'daisy',
    prescriptionId: 'rx-daisy-vitamin-d',
    medicationName: 'Vitamin D',
    dose: { amount: 400, unit: 'units' },
    route: 'oral',
    scheduledTime: Timestamp.fromDate(today8am),
    administrationMethod: 'in_feed',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
  // Daisy - 14:00 medications (pending)
  {
    id: 'med-daisy-caffeine-2pm',
    babyId: 'daisy',
    prescriptionId: 'rx-daisy-caffeine',
    medicationName: 'Caffeine Citrate',
    dose: { amount: 5, unit: 'mg/kg' },
    route: 'oral',
    scheduledTime: Timestamp.fromDate(today2pm),
    administrationMethod: 'in_feed',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
  // Elsa - 08:00 medications (pending)
  {
    id: 'med-elsa-caffeine-today',
    babyId: 'elsa',
    prescriptionId: 'rx-elsa-caffeine',
    medicationName: 'Caffeine Citrate',
    dose: { amount: 5, unit: 'mg/kg' },
    route: 'oral',
    scheduledTime: Timestamp.fromDate(today8am),
    administrationMethod: 'in_feed',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'med-elsa-dex-8am',
    babyId: 'elsa',
    prescriptionId: 'rx-elsa-dexamethasone',
    medicationName: 'Dexamethasone',
    dose: { amount: 0.15, unit: 'mg/kg' },
    route: 'IV',
    scheduledTime: Timestamp.fromDate(today8am),
    administrationMethod: 'separately',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'med-elsa-vitamin-d-today',
    babyId: 'elsa',
    prescriptionId: 'rx-elsa-vitamin-d',
    medicationName: 'Vitamin D',
    dose: { amount: 400, unit: 'units' },
    route: 'oral',
    scheduledTime: Timestamp.fromDate(today8am),
    administrationMethod: 'in_feed',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'med-elsa-dex-8pm',
    babyId: 'elsa',
    prescriptionId: 'rx-elsa-dexamethasone',
    medicationName: 'Dexamethasone',
    dose: { amount: 0.15, unit: 'mg/kg' },
    route: 'IV',
    scheduledTime: Timestamp.fromDate(today8pm),
    administrationMethod: 'separately',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
];

// Care Plans
export const DEMO_CARE_PLANS: CarePlan[] = [
  {
    id: 'cp-daisy-feeding',
    babyId: 'daisy',
    type: 'feeding',
    title: 'Feeding Plan',
    description: 'Progressive feeding plan for premature infant',
    instructions: [
      'Feed every 3 hours',
      'Monitor tolerance after each feed',
      'Fortify with 2 scoops per 100ml',
      'Target 35ml per feed',
    ],
    feedingSchedule: {
      frequency: 3,
      volumePerFeed: 35,
      feedType: 'Fortified EBM',
      route: 'NG tube',
    },
    status: 'active',
    effectiveFrom: daysAgo(5),
    createdBy: 'emma-consultant',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'cp-elsa-feeding',
    babyId: 'elsa',
    type: 'feeding',
    title: 'Feeding Plan',
    description: 'Gradual feeding advancement for extreme preterm',
    instructions: [
      'Feed every 3 hours',
      'Monitor for NEC signs',
      'Fortify with 4 scoops per 100ml',
      'Target 25ml per feed',
      'Aspirate before each feed',
    ],
    feedingSchedule: {
      frequency: 3,
      volumePerFeed: 25,
      feedType: 'Fortified EBM',
      route: 'NG tube',
    },
    status: 'active',
    effectiveFrom: daysAgo(12),
    createdBy: 'emma-consultant',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
];

// Feeding Records
export let DEMO_FEEDS: FeedingRecord[] = [
  {
    id: 'feed-daisy-yesterday',
    babyId: 'daisy',
    feedTime: hoursAgo(15),
    recordedBy: 'sarah-nurse',
    feedType: 'fortified_EBM',
    volume: { prescribed: 35, actual: 35 },
    route: 'NG_tube',
    medicationsIncluded: [
      {
        medicationAdministrationId: 'med-daisy-yesterday-1',
        medicationName: 'Caffeine Citrate',
        confirmed: true,
      },
    ],
    tolerance: 'good',
    createdAt: hoursAgo(15),
    updatedAt: hoursAgo(15),
  },
];

// Vital Signs
export const DEMO_VITAL_SIGNS: VitalSign[] = [
  {
    id: 'vs-daisy-latest',
    babyId: 'daisy',
    recordedAt: hoursAgo(1),
    recordedBy: 'sarah-nurse',
    weight: { value: 1875 },
    temperature: { value: 36.8, site: 'axillary' },
    heartRate: { value: 145 },
    respiratoryRate: { value: 48 },
    oxygenSaturation: {
      value: 97,
      oxygenSupport: { type: 'room air' },
    },
    createdAt: hoursAgo(1),
  },
  {
    id: 'vs-elsa-latest',
    babyId: 'elsa',
    recordedAt: hoursAgo(2),
    recordedBy: 'sarah-nurse',
    weight: { value: 1165 },
    temperature: { value: 36.9, site: 'skin' },
    heartRate: { value: 152 },
    respiratoryRate: { value: 55 },
    oxygenSaturation: {
      value: 94,
      oxygenSupport: { type: 'nasal cannula', fiO2: 25 },
    },
    createdAt: hoursAgo(2),
  },
];

// Mock data store
export const mockDataStore = {
  users: DEMO_USERS,
  babies: DEMO_BABIES,
  prescriptions: DEMO_PRESCRIPTIONS,
  medications: DEMO_MEDICATIONS,
  carePlans: DEMO_CARE_PLANS,
  feeds: DEMO_FEEDS,
  vitalSigns: DEMO_VITAL_SIGNS,
};
