import { Timestamp } from 'firebase/firestore';
import type {
  Baby,
  User,
  MedicationPrescription,
  MedicationAdministration,
  FeedingRecord,
  CarePlan,
  VitalSign,
  Parent,
  BabyHousing,
  ConsentRecord,
  PeripheralCentralLineRecord,
  NasoOrogastricTubeInsertion,
  BloodGasResult,
  FluidBalanceRecord,
  TwentyFourHourResume,
  InfectionRecord,
  DischargeChecklist,
  DailyWeightChart,
  AdmissionAssessment,
  SampleCollectionMetadata,
  TransfusionRecord,
  PhototherapyRecord,
  EnhancedCarePlan,
  NursingTask,
  TaskCompletionSummary
} from '../types';
import { ROLE_PERMISSIONS } from '../types';
import { generateAllTasks } from '../utils/taskGenerator';

// Helper to create timestamps
const now = () => Timestamp.now();
const daysAgo = (days: number) => Timestamp.fromDate(new Date(Date.now() - days * 24 * 60 * 60 * 1000));
const hoursAgo = (hours: number) => Timestamp.fromDate(new Date(Date.now() - hours * 60 * 60 * 1000));

// Demo Users
export const DEMO_USERS: User[] = [
  {
    id: 'sarah-nurse',
    email: 'sarah.nurse@demo.nicu',
    firstName: 'Sarah',
    lastName: 'Johnson',
    role: 'bedside_nurse',
    permissions: ROLE_PERMISSIONS.bedside_nurse,
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'emma-consultant',
    email: 'emma.consultant@demo.nicu',
    firstName: 'Dr. Emma',
    lastName: 'Williams',
    role: 'consultant',
    permissions: ROLE_PERMISSIONS.consultant,
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'james-doctor',
    email: 'james.doctor@demo.nicu',
    firstName: 'Dr. James',
    lastName: 'Chen',
    role: 'junior_doctor',
    permissions: ROLE_PERMISSIONS.junior_doctor,
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'maria-manager',
    email: 'maria.manager@demo.nicu',
    firstName: 'Maria',
    lastName: 'Garcia',
    role: 'ward_manager',
    permissions: ROLE_PERMISSIONS.ward_manager,
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'tom-physio',
    email: 'tom.physio@demo.nicu',
    firstName: 'Tom',
    lastName: 'Andrews',
    role: 'physiotherapist',
    permissions: ROLE_PERMISSIONS.physiotherapist,
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'rachel-parent',
    email: 'rachel.parent@demo.nicu',
    firstName: 'Rachel',
    lastName: 'Smith',
    role: 'parent',
    permissions: ROLE_PERMISSIONS.parent,
    babyIds: ['daisy'],
    createdAt: now(),
    updatedAt: now(),
  },
];

// Demo Babies
export const DEMO_BABIES: Baby[] = [
  {
    id: 'daisy',
    nhsNumber: '9876543210',
    hospitalNumber: 'NH001234',
    firstName: 'Daisy',
    lastName: 'Smith',
    dateOfBirth: daysAgo(5),
    gestationalAgeAtBirth: { weeks: 32, days: 4 },
    birthWeight: 1850,
    birthLength: 42,
    birthHeadCircumference: 29.5,
    sex: 'female',
    birthDetails: {
      deliveryMethod: 'emergency_CS',
      apgarScores: {
        oneMin: 7,
        fiveMin: 9,
        tenMin: 9,
      },
      resuscitation: true,
      resuscitationDetails: 'Facial oxygen and stimulation for 2 minutes',
      birthLocation: 'St Mary\'s Hospital Labour Ward',
      plurality: 'singleton',
      complications: ['Fetal distress', 'Meconium-stained liquor'],
    },
    motherNhsNumber: '1234567890',
    fatherNhsNumber: '0987654321',
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    bedNumber: 'Room 1',
    roomNumber: 'NICU-Bay-A',
    admissionDate: daysAgo(5),
    admissionDiagnoses: ['Prematurity', 'Respiratory distress syndrome', 'Rule out sepsis'],
    diagnoses: ['Prematurity', 'Respiratory distress syndrome'],
    outcomeStatus: 'inpatient',
    expectedDischargeDate: daysAgo(-10),
    parentUserIds: ['rachel-parent'],
    primaryNurseId: 'sarah-nurse',
    consultantId: 'emma-consultant',
    isActive: true,
    createdAt: daysAgo(5),
    updatedAt: now(),
    createdBy: 'system',
  },
  {
    id: 'elsa',
    nhsNumber: '5432167890',
    hospitalNumber: 'NH001235',
    firstName: 'Elsa',
    lastName: 'Brown',
    dateOfBirth: daysAgo(12),
    gestationalAgeAtBirth: { weeks: 28, days: 2 },
    birthWeight: 1120,
    birthLength: 36,
    birthHeadCircumference: 25.5,
    sex: 'female',
    birthDetails: {
      deliveryMethod: 'emergency_CS',
      apgarScores: {
        oneMin: 4,
        fiveMin: 7,
        tenMin: 8,
      },
      resuscitation: true,
      resuscitationDetails: 'Intubation and ventilation for 5 minutes, surfactant given',
      birthLocation: 'St Mary\'s Hospital Labour Ward',
      plurality: 'twin',
      complications: ['Severe prematurity', 'Twin-twin transfusion syndrome (recipient)'],
    },
    motherNhsNumber: '2468135790',
    unitId: 'demo-unit-1',
    trustId: 'demo-trust-1',
    bedNumber: 'Room 2',
    roomNumber: 'NICU-Bay-B',
    admissionDate: daysAgo(12),
    admissionDiagnoses: ['Extreme prematurity', 'RDS requiring ventilation', 'Rule out sepsis', 'TTTS'],
    diagnoses: ['Extreme prematurity', 'Bronchopulmonary dysplasia', 'Patent ductus arteriosus'],
    outcomeStatus: 'inpatient',
    parentUserIds: [],
    primaryNurseId: 'sarah-nurse',
    consultantId: 'emma-consultant',
    isActive: true,
    createdAt: daysAgo(12),
    updatedAt: now(),
    createdBy: 'system',
  },
];

// Medication Prescriptions
export const DEMO_PRESCRIPTIONS: MedicationPrescription[] = [
  {
    id: 'rx-daisy-caffeine',
    babyId: 'daisy',
    medicationName: 'Caffeine Citrate',
    dose: { amount: 5, unit: 'mg/kg' },
    route: 'oral',
    frequency: 'OD',
    timings: ['08:00'],
    startDate: daysAgo(5),
    indication: 'Apnoea of prematurity',
    canBeGivenInFeed: true,
    mustBeGivenSeparately: false,
    status: 'approved',
    prescribedBy: 'emma-consultant',
    prescribedAt: daysAgo(5),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'rx-daisy-vitamin-d',
    babyId: 'daisy',
    medicationName: 'Vitamin D',
    dose: { amount: 400, unit: 'units' },
    route: 'oral',
    frequency: 'OD',
    timings: ['08:00'],
    startDate: daysAgo(5),
    indication: 'Prematurity supplementation',
    canBeGivenInFeed: true,
    mustBeGivenSeparately: false,
    status: 'approved',
    prescribedBy: 'emma-consultant',
    prescribedAt: daysAgo(5),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'rx-elsa-caffeine',
    babyId: 'elsa',
    medicationName: 'Caffeine Citrate',
    dose: { amount: 5, unit: 'mg/kg' },
    route: 'oral',
    frequency: 'OD',
    timings: ['08:00'],
    startDate: daysAgo(12),
    indication: 'Apnoea of prematurity',
    canBeGivenInFeed: true,
    mustBeGivenSeparately: false,
    status: 'approved',
    prescribedBy: 'emma-consultant',
    prescribedAt: daysAgo(12),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
  {
    id: 'rx-elsa-dexamethasone',
    babyId: 'elsa',
    medicationName: 'Dexamethasone',
    dose: { amount: 0.15, unit: 'mg/kg' },
    route: 'IV',
    frequency: 'BD',
    timings: ['08:00', '20:00'],
    startDate: daysAgo(10),
    indication: 'Bronchopulmonary dysplasia',
    canBeGivenInFeed: false,
    mustBeGivenSeparately: true,
    status: 'approved',
    prescribedBy: 'emma-consultant',
    prescribedAt: daysAgo(10),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: 'rx-elsa-vitamin-d',
    babyId: 'elsa',
    medicationName: 'Vitamin D',
    dose: { amount: 400, unit: 'units' },
    route: 'oral',
    frequency: 'OD',
    timings: ['08:00'],
    startDate: daysAgo(12),
    indication: 'Prematurity supplementation',
    canBeGivenInFeed: true,
    mustBeGivenSeparately: false,
    status: 'approved',
    prescribedBy: 'emma-consultant',
    prescribedAt: daysAgo(12),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
];

// Medication Administrations (for today)
const today8am = new Date();
today8am.setHours(8, 0, 0, 0);
const today2pm = new Date();
today2pm.setHours(14, 0, 0, 0);
const today8pm = new Date();
today8pm.setHours(20, 0, 0, 0);

export let DEMO_MEDICATIONS: MedicationAdministration[] = [
  // Daisy - 08:00 medications (pending)
  {
    id: 'med-daisy-caffeine-today',
    babyId: 'daisy',
    prescriptionId: 'rx-daisy-caffeine',
    medicationName: 'Caffeine Citrate',
    dose: { amount: 5, unit: 'mg/kg' },
    route: 'oral',
    scheduledTime: Timestamp.fromDate(today8am),
    administrationMethod: 'in_feed',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'med-daisy-vitamin-d-today',
    babyId: 'daisy',
    prescriptionId: 'rx-daisy-vitamin-d',
    medicationName: 'Vitamin D',
    dose: { amount: 400, unit: 'units' },
    route: 'oral',
    scheduledTime: Timestamp.fromDate(today8am),
    administrationMethod: 'in_feed',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
  // Daisy - 14:00 medications (pending)
  {
    id: 'med-daisy-caffeine-2pm',
    babyId: 'daisy',
    prescriptionId: 'rx-daisy-caffeine',
    medicationName: 'Caffeine Citrate',
    dose: { amount: 5, unit: 'mg/kg' },
    route: 'oral',
    scheduledTime: Timestamp.fromDate(today2pm),
    administrationMethod: 'in_feed',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
  // Elsa - 08:00 medications (pending)
  {
    id: 'med-elsa-caffeine-today',
    babyId: 'elsa',
    prescriptionId: 'rx-elsa-caffeine',
    medicationName: 'Caffeine Citrate',
    dose: { amount: 5, unit: 'mg/kg' },
    route: 'oral',
    scheduledTime: Timestamp.fromDate(today8am),
    administrationMethod: 'in_feed',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'med-elsa-dex-8am',
    babyId: 'elsa',
    prescriptionId: 'rx-elsa-dexamethasone',
    medicationName: 'Dexamethasone',
    dose: { amount: 0.15, unit: 'mg/kg' },
    route: 'IV',
    scheduledTime: Timestamp.fromDate(today8am),
    administrationMethod: 'separately',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'med-elsa-vitamin-d-today',
    babyId: 'elsa',
    prescriptionId: 'rx-elsa-vitamin-d',
    medicationName: 'Vitamin D',
    dose: { amount: 400, unit: 'units' },
    route: 'oral',
    scheduledTime: Timestamp.fromDate(today8am),
    administrationMethod: 'in_feed',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: 'med-elsa-dex-8pm',
    babyId: 'elsa',
    prescriptionId: 'rx-elsa-dexamethasone',
    medicationName: 'Dexamethasone',
    dose: { amount: 0.15, unit: 'mg/kg' },
    route: 'IV',
    scheduledTime: Timestamp.fromDate(today8pm),
    administrationMethod: 'separately',
    status: 'pending',
    createdAt: now(),
    updatedAt: now(),
  },
];

// Care Plans
export const DEMO_CARE_PLANS: CarePlan[] = [
  {
    id: 'cp-daisy-feeding',
    babyId: 'daisy',
    type: 'feeding',
    title: 'Feeding Plan',
    description: 'Progressive feeding plan for premature infant',
    instructions: [
      'Feed every 3 hours',
      'Monitor tolerance after each feed',
      'Fortify with 2 scoops per 100ml',
      'Target 35ml per feed',
    ],
    feedingSchedule: {
      frequency: 3,
      volumePerFeed: 35,
      feedType: 'Fortified EBM',
      route: 'NG tube',
    },
    status: 'active',
    effectiveFrom: daysAgo(5),
    createdBy: 'emma-consultant',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'cp-elsa-feeding',
    babyId: 'elsa',
    type: 'feeding',
    title: 'Feeding Plan',
    description: 'Gradual feeding advancement for extreme preterm',
    instructions: [
      'Feed every 3 hours',
      'Monitor for NEC signs',
      'Fortify with 4 scoops per 100ml',
      'Target 25ml per feed',
      'Aspirate before each feed',
    ],
    feedingSchedule: {
      frequency: 3,
      volumePerFeed: 25,
      feedType: 'Fortified EBM',
      route: 'NG tube',
    },
    status: 'active',
    effectiveFrom: daysAgo(12),
    createdBy: 'emma-consultant',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
];

// Feeding Records
export let DEMO_FEEDS: FeedingRecord[] = [
  {
    id: 'feed-daisy-yesterday',
    babyId: 'daisy',
    feedTime: hoursAgo(15),
    recordedBy: 'sarah-nurse',
    feedType: 'fortified_EBM',
    volume: { prescribed: 35, actual: 35 },
    route: 'NG_tube',
    medicationsIncluded: [
      {
        medicationAdministrationId: 'med-daisy-yesterday-1',
        medicationName: 'Caffeine Citrate',
        confirmed: true,
      },
    ],
    tolerance: 'good',
    createdAt: hoursAgo(15),
    updatedAt: hoursAgo(15),
  },
];

// Vital Signs
export const DEMO_VITAL_SIGNS: VitalSign[] = [
  {
    id: 'vs-daisy-latest',
    babyId: 'daisy',
    recordedAt: hoursAgo(1),
    recordedBy: 'sarah-nurse',
    weight: { value: 1875 },
    temperature: { value: 36.8, site: 'axillary' },
    heartRate: { value: 145 },
    respiratoryRate: { value: 48 },
    oxygenSaturation: {
      value: 97,
      oxygenSupport: { type: 'room air' },
    },
    createdAt: hoursAgo(1),
  },
  {
    id: 'vs-elsa-latest',
    babyId: 'elsa',
    recordedAt: hoursAgo(2),
    recordedBy: 'sarah-nurse',
    weight: { value: 1165 },
    temperature: { value: 36.9, site: 'skin' },
    heartRate: { value: 152 },
    respiratoryRate: { value: 55 },
    oxygenSaturation: {
      value: 94,
      oxygenSupport: { type: 'nasal cannula', fiO2: 25 },
    },
    createdAt: hoursAgo(2),
  },
];

// Parents
export const DEMO_PARENTS: Parent[] = [
  {
    id: 'parent-rachel-smith',
    babyIds: ['daisy'],
    nhsNumber: '1234567890',
    firstName: 'Rachel',
    lastName: 'Smith',
    dateOfBirth: Timestamp.fromDate(new Date('1990-05-15')),
    age: 34,
    occupation: 'Primary School Teacher',
    ethnicity: 'White British',
    religion: 'Christian',
    firstLanguage: 'English',
    interpreterRequired: false,
    relationship: 'mother',
    parentalResponsibility: true,
    contactDetails: {
      mobilePhone: '07700 900123',
      homePhone: '01234 567890',
      email: 'rachel.smith@email.com',
      preferredContactMethod: 'mobile',
    },
    address: {
      line1: '42 Maple Avenue',
      line2: 'Riverside',
      city: 'Manchester',
      postcode: 'M1 3AB',
      sameAsBaby: true,
    },
    relationshipStatus: 'married',
    isEmergencyContact: true,
    emergencyContactPriority: 1,
    visitLog: [
      { date: daysAgo(5), duration: 240, activities: ['Kangaroo care', 'Expressed milk'] },
      { date: daysAgo(4), duration: 180, activities: ['Kangaroo care', 'Nappy change'] },
      { date: daysAgo(3), duration: 300, activities: ['Kangaroo care', 'Feeding', 'Skin-to-skin'] },
      { date: daysAgo(2), duration: 200, activities: ['Feeding', 'Nappy change'] },
      { date: daysAgo(1), duration: 250, activities: ['Kangaroo care', 'Feeding'] },
    ],
    createdAt: daysAgo(5),
    updatedAt: now(),
  },
  {
    id: 'parent-sophie-brown',
    babyIds: ['elsa'],
    nhsNumber: '2468135790',
    firstName: 'Sophie',
    lastName: 'Brown',
    dateOfBirth: Timestamp.fromDate(new Date('1988-08-22')),
    age: 36,
    occupation: 'NHS Administrator',
    ethnicity: 'White British',
    religion: 'None',
    firstLanguage: 'English',
    interpreterRequired: false,
    relationship: 'mother',
    parentalResponsibility: true,
    contactDetails: {
      mobilePhone: '07700 900456',
      email: 'sophie.brown@email.com',
      preferredContactMethod: 'mobile',
    },
    address: {
      line1: '15 Oak Street',
      city: 'Manchester',
      postcode: 'M2 5CD',
      sameAsBaby: true,
    },
    relationshipStatus: 'separated',
    isEmergencyContact: true,
    emergencyContactPriority: 1,
    visitLog: [
      { date: daysAgo(12), duration: 120, activities: ['Brief visit', 'Expressed milk'] },
      { date: daysAgo(10), duration: 180, activities: ['Kangaroo care'] },
      { date: daysAgo(8), duration: 150, activities: ['Visit'] },
      { date: daysAgo(5), duration: 200, activities: ['Kangaroo care', 'Expressed milk'] },
      { date: daysAgo(2), duration: 180, activities: ['Kangaroo care'] },
    ],
    createdAt: daysAgo(12),
    updatedAt: now(),
  },
];

// Housing Information
export const DEMO_HOUSING: BabyHousing[] = [
  {
    id: 'housing-daisy',
    babyId: 'daisy',
    livingArrangements: 'owns_home',
    address: {
      line1: '42 Maple Avenue',
      line2: 'Riverside',
      city: 'Manchester',
      postcode: 'M1 3AB',
    },
    numberOfBedrooms: 3,
    householdSmoker: false,
    householdMembers: [
      { name: 'Rachel Smith', relationship: 'Mother', age: 34 },
      { name: 'David Smith', relationship: 'Father', age: 36 },
    ],
    otherChildren: [
      { name: 'Oliver Smith', age: 5, relationship: 'Sibling' },
    ],
    socialServicesInvolved: false,
    safeguardingConcerns: false,
    childProtectionPlan: false,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'housing-elsa',
    babyId: 'elsa',
    livingArrangements: 'rents_privately',
    address: {
      line1: '15 Oak Street',
      city: 'Manchester',
      postcode: 'M2 5CD',
    },
    numberOfBedrooms: 2,
    householdSmoker: false,
    householdMembers: [
      { name: 'Sophie Brown', relationship: 'Mother', age: 36 },
    ],
    otherChildren: [],
    socialServicesInvolved: false,
    safeguardingConcerns: false,
    childProtectionPlan: false,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
];

// Consent Records
export const DEMO_CONSENTS: ConsentRecord[] = [
  {
    id: 'consent-daisy-treatment',
    babyId: 'daisy',
    consentType: 'treatment',
    specificProcedure: 'NICU admission and standard care',
    consentedBy: {
      personId: 'parent-rachel-smith',
      name: 'Rachel Smith',
      relationship: 'mother',
    },
    dateObtained: daysAgo(5),
    obtainedBy: 'emma-consultant',
    validFrom: daysAgo(5),
    withdrawn: false,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'consent-elsa-treatment',
    babyId: 'elsa',
    consentType: 'treatment',
    specificProcedure: 'NICU admission, ventilation and standard care',
    consentedBy: {
      personId: 'parent-sophie-brown',
      name: 'Sophie Brown',
      relationship: 'mother',
    },
    dateObtained: daysAgo(12),
    obtainedBy: 'emma-consultant',
    validFrom: daysAgo(12),
    withdrawn: false,
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
];

// IV Lines
export const DEMO_IV_LINES: PeripheralCentralLineRecord[] = [
  {
    id: 'line-daisy-peripheral',
    babyId: 'daisy',
    lineType: 'peripheral_IV',
    insertionDate: daysAgo(3),
    insertionTime: '14:30',
    insertionSite: 'Right hand dorsum',
    insertedBy: 'sarah-nurse',
    gaugeSize: '24G',
    length: 2.5,
    positionVerified: true,
    verificationMethod: 'blood_gas',
    securingMethod: 'Transparent dressing with Tegaderm',
    cleaningSolutionUsed: 'Chlorhexidine 0.5%',
    dressingChanges: [
      {
        date: daysAgo(1),
        performedBy: 'sarah-nurse',
        siteAppearance: 'clean',
        notes: 'No signs of inflammation',
      },
    ],
    patencyChecks: [
      { date: daysAgo(2), patent: true, flushedWith: 'Normal saline 0.5ml' },
      { date: daysAgo(1), patent: true, flushedWith: 'Normal saline 0.5ml' },
      { date: now(), patent: true, flushedWith: 'Normal saline 0.5ml' },
    ],
    complications: [],
    isActive: true,
    createdAt: daysAgo(3),
    updatedAt: now(),
  },
  {
    id: 'line-elsa-picc',
    babyId: 'elsa',
    lineType: 'PICC',
    insertionDate: daysAgo(10),
    insertionTime: '10:15',
    insertionSite: 'Right arm - basilic vein',
    insertedBy: 'emma-consultant',
    gaugeSize: '1Fr',
    length: 8,
    tipPosition: 'IVC/RA junction',
    positionVerified: true,
    verificationMethod: 'xray',
    verificationDate: daysAgo(10),
    securingMethod: 'Sutures and transparent dressing',
    cleaningSolutionUsed: 'Chlorhexidine 0.5%',
    dressingChanges: [
      {
        date: daysAgo(7),
        performedBy: 'sarah-nurse',
        siteAppearance: 'clean',
      },
      {
        date: daysAgo(3),
        performedBy: 'sarah-nurse',
        siteAppearance: 'clean',
      },
    ],
    patencyChecks: [
      { date: daysAgo(5), patent: true },
      { date: daysAgo(2), patent: true },
      { date: now(), patent: true },
    ],
    complications: [],
    isActive: true,
    createdAt: daysAgo(10),
    updatedAt: now(),
  },
];

// NG Tubes
export const DEMO_NG_TUBES: NasoOrogastricTubeInsertion[] = [
  {
    id: 'tube-daisy-ng',
    babyId: 'daisy',
    tubeType: 'NG',
    insertionDateTime: daysAgo(5),
    tubeSize: '6Fr',
    lengthInserted: 12,
    nostrilSide: 'right',
    nexMeasurement: 12,
    positionVerified: true,
    verificationMethod: 'pH',
    aspiratepH: 4.5,
    securingMethod: 'Tegaderm to right cheek',
    externalLength: 4,
    tubeChecks: [
      { date: daysAgo(4), time: '08:00', positionConfirmed: true, method: 'pH', pH: 4.2, checkedBy: 'sarah-nurse' },
      { date: daysAgo(3), time: '08:00', positionConfirmed: true, method: 'pH', pH: 4.8, checkedBy: 'sarah-nurse' },
      { date: daysAgo(2), time: '08:00', positionConfirmed: true, method: 'pH', pH: 4.5, checkedBy: 'sarah-nurse' },
      { date: daysAgo(1), time: '08:00', positionConfirmed: true, method: 'pH', pH: 4.3, checkedBy: 'sarah-nurse' },
    ],
    complications: [],
    isActive: true,
    insertedBy: 'sarah-nurse',
    createdAt: daysAgo(5),
    updatedAt: now(),
  },
  {
    id: 'tube-elsa-ng',
    babyId: 'elsa',
    tubeType: 'NG',
    insertionDateTime: daysAgo(12),
    tubeSize: '5Fr',
    lengthInserted: 10,
    nostrilSide: 'left',
    nexMeasurement: 10,
    positionVerified: true,
    verificationMethod: 'xray',
    xrayDate: daysAgo(12),
    securingMethod: 'Tegaderm to left cheek',
    externalLength: 3,
    tubeChecks: [
      { date: daysAgo(10), time: '08:00', positionConfirmed: true, method: 'pH', pH: 4.1, checkedBy: 'sarah-nurse' },
      { date: daysAgo(7), time: '08:00', positionConfirmed: true, method: 'pH', pH: 4.6, checkedBy: 'sarah-nurse' },
      { date: daysAgo(4), time: '08:00', positionConfirmed: true, method: 'pH', pH: 4.3, checkedBy: 'sarah-nurse' },
      { date: daysAgo(1), time: '08:00', positionConfirmed: true, method: 'pH', pH: 4.4, checkedBy: 'sarah-nurse' },
    ],
    complications: [],
    isActive: true,
    insertedBy: 'sarah-nurse',
    createdAt: daysAgo(12),
    updatedAt: now(),
  },
];

// Blood Gas Results
export const DEMO_BLOOD_GAS: BloodGasResult[] = [
  // Daisy - Day 5 (admission)
  {
    id: 'bg-daisy-day5',
    babyId: 'daisy',
    sampleDate: daysAgo(5),
    sampleTime: '10:30',
    sampleType: 'capillary',
    sampleSite: 'Right heel',
    pH: 7.32,
    pCO2: 5.8,
    pO2: 9.2,
    baseExcess: -3.5,
    HCO3: 22,
    lactate: 1.8,
    hemoglobin: 168,
    glucose: 4.2,
    takenBy: 'sarah-nurse',
    checkedBy: 'james-doctor',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  // Daisy - Day 3
  {
    id: 'bg-daisy-day3',
    babyId: 'daisy',
    sampleDate: daysAgo(3),
    sampleTime: '08:15',
    sampleType: 'capillary',
    sampleSite: 'Left heel',
    pH: 7.36,
    pCO2: 5.2,
    pO2: 10.1,
    baseExcess: -1.2,
    HCO3: 24,
    lactate: 1.2,
    hemoglobin: 162,
    glucose: 4.5,
    takenBy: 'sarah-nurse',
    checkedBy: 'james-doctor',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  // Elsa - Day 12 (admission, ventilated)
  {
    id: 'bg-elsa-day12',
    babyId: 'elsa',
    sampleDate: daysAgo(12),
    sampleTime: '11:00',
    sampleType: 'arterial',
    sampleSite: 'UAC',
    pH: 7.28,
    pCO2: 6.5,
    pO2: 8.5,
    baseExcess: -5.2,
    HCO3: 20,
    lactate: 2.8,
    hemoglobin: 152,
    glucose: 3.8,
    ventilatorSettings: {
      mode: 'SIMV',
      fiO2: 40,
      peep: 6,
      pip: 20,
      rate: 40,
    },
    takenBy: 'sarah-nurse',
    checkedBy: 'emma-consultant',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
  // Elsa - Day 8
  {
    id: 'bg-elsa-day8',
    babyId: 'elsa',
    sampleDate: daysAgo(8),
    sampleTime: '09:30',
    sampleType: 'capillary',
    sampleSite: 'Right heel',
    pH: 7.33,
    pCO2: 5.5,
    pO2: 9.8,
    baseExcess: -2.5,
    HCO3: 22,
    lactate: 1.5,
    hemoglobin: 145,
    glucose: 4.1,
    takenBy: 'sarah-nurse',
    checkedBy: 'james-doctor',
    createdAt: daysAgo(8),
    updatedAt: daysAgo(8),
  },
];

// Fluid Balance Records (last 24 hours)
export const DEMO_FLUID_BALANCE: FluidBalanceRecord[] = [
  // Daisy - Yesterday
  {
    id: 'fb-daisy-slot1',
    babyId: 'daisy',
    date: daysAgo(1),
    timeSlot: '00:00-06:00',
    intake: {
      enteral: 70,
      medications: 2,
      total: 72,
    },
    output: {
      urine: 15,
      stool: 5,
      total: 20,
    },
    netBalance: 52,
    cumulativeBalance: 52,
    recordedBy: 'sarah-nurse',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'fb-daisy-slot2',
    babyId: 'daisy',
    date: daysAgo(1),
    timeSlot: '06:00-12:00',
    intake: {
      enteral: 70,
      medications: 2,
      total: 72,
    },
    output: {
      urine: 18,
      stool: 8,
      total: 26,
    },
    netBalance: 46,
    cumulativeBalance: 98,
    recordedBy: 'sarah-nurse',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  // Elsa - Yesterday
  {
    id: 'fb-elsa-slot1',
    babyId: 'elsa',
    date: daysAgo(1),
    timeSlot: '00:00-06:00',
    intake: {
      iv: 25,
      enteral: 50,
      medications: 3,
      total: 78,
    },
    output: {
      urine: 12,
      stool: 3,
      aspirates: 5,
      total: 20,
    },
    netBalance: 58,
    cumulativeBalance: 58,
    recordedBy: 'sarah-nurse',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

// 24-Hour Resume
export const DEMO_24HR_RESUME: TwentyFourHourResume[] = [
  {
    id: 'resume-daisy-yesterday',
    babyId: 'daisy',
    resumeDate: daysAgo(1),
    ageInDays: 4,
    correctedGestationalAge: { weeks: 33, days: 1 },
    respiratory: {
      mode: 'room_air',
      oxygenRange: '21%',
      spontaneousBreathing: true,
      extubationPlanned: false,
    },
    cardiovascular: {
      heartRateRange: '130-155',
      bloodPressureRange: '50-60/30-40',
      meanBP: 45,
      perfusion: 'good',
      capillaryRefillTime: 2,
    },
    temperatureRange: '36.5-37.1°C',
    events: {
      apnoeas: 0,
      bradycardias: 0,
      desaturations: 0,
    },
    urineOutput: {
      totalVolume: 95,
      mlPerKgPerHour: 2.1,
    },
    bowelAction: {
      passed: true,
      frequency: 4,
      description: 'Normal yellow seedy stools',
    },
    fluidsAndNutrition: {
      totalFluids: 150,
      enteralIntake: 150,
      parenteralIntake: 0,
      feedingMethod: 'fortified',
      feedVolume: 35,
      feedFrequency: '3-hourly',
      feedTolerance: 'good',
      vomits: 0,
      aspirates: 'Minimal',
    },
    bloodProducts: {},
    totalBloodTaken: 0.5,
    jaundice: {
      phototherapy: false,
    },
    medications: ['Caffeine Citrate 5mg/kg OD', 'Vitamin D 400 units OD'],
    investigations: {
      bloodTests: ['Capillary blood gas'],
    },
    plan: 'Continue feeding advancement. Aim for 40ml feeds by tomorrow. Monitor apnoeas. Consider discharge planning next week.',
    concerns: [],
    actions: [],
    completedBy: 'james-doctor',
    reviewedBy: 'emma-consultant',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
  {
    id: 'resume-elsa-yesterday',
    babyId: 'elsa',
    resumeDate: daysAgo(1),
    ageInDays: 11,
    correctedGestationalAge: { weeks: 29, days: 6 },
    respiratory: {
      mode: 'nasal_cannula',
      settings: {
        fiO2Range: '23-28%',
      },
      oxygenRange: '23-28%',
      spontaneousBreathing: true,
      extubationPlanned: false,
    },
    cardiovascular: {
      heartRateRange: '145-165',
      bloodPressureRange: '42-52/25-35',
      meanBP: 38,
      perfusion: 'adequate',
      capillaryRefillTime: 3,
    },
    temperatureRange: '36.7-37.3°C',
    events: {
      apnoeas: 2,
      bradycardias: 1,
      desaturations: 3,
    },
    urineOutput: {
      totalVolume: 68,
      mlPerKgPerHour: 2.4,
    },
    bowelAction: {
      passed: true,
      frequency: 2,
      description: 'Soft green stools',
    },
    fluidsAndNutrition: {
      totalFluids: 160,
      enteralIntake: 120,
      parenteralIntake: 40,
      feedingMethod: 'fortified',
      feedVolume: 25,
      feedFrequency: '3-hourly',
      feedTolerance: 'moderate',
      vomits: 0,
      aspirates: 'Small amounts, bile-stained',
    },
    bloodProducts: {},
    totalBloodTaken: 1.2,
    jaundice: {
      phototherapy: false,
    },
    medications: [
      'Caffeine Citrate 5mg/kg OD',
      'Dexamethasone 0.15mg/kg BD (for BPD)',
      'Vitamin D 400 units OD',
    ],
    investigations: {
      bloodTests: ['Capillary blood gas', 'CRP'],
    },
    plan: 'Continue respiratory support. Wean oxygen as tolerated. Slowly advance feeds. Monitor for PDA - echo planned. Continue dexamethasone course.',
    concerns: ['Ongoing oxygen requirement', 'PDA monitoring'],
    actions: ['Echo booked for tomorrow', 'Dietitian review'],
    completedBy: 'james-doctor',
    reviewedBy: 'emma-consultant',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

// Infection Records
export const DEMO_INFECTIONS: InfectionRecord[] = [
  {
    id: 'infection-elsa-eos',
    babyId: 'elsa',
    episodeStartDate: daysAgo(12),
    episodeEndDate: daysAgo(7),
    infectionType: 'ruled_out',
    infectionCategory: 'early_onset_sepsis',
    clinicalSigns: ['Prematurity', 'Respiratory distress', 'Temperature instability'],
    microbiology: {
      samplesTaken: [
        {
          type: 'blood_culture',
          date: daysAgo(12),
          result: 'No growth after 48 hours',
        },
        {
          type: 'surface_swabs',
          date: daysAgo(12),
          result: 'Normal flora',
        },
      ],
    },
    infectionMarkers: [
      { crp: 8, wbc: 12.5, neutrophils: 6.2, platelets: 245 },
      { crp: 5, wbc: 11.8, neutrophils: 5.8, platelets: 250 },
    ],
    antibiotics: [
      {
        drug: 'Benzylpenicillin',
        startDate: daysAgo(12),
        stopDate: daysAgo(7),
        durationDays: 5,
        indication: 'Suspected early onset sepsis',
      },
      {
        drug: 'Gentamicin',
        startDate: daysAgo(12),
        stopDate: daysAgo(7),
        durationDays: 5,
        indication: 'Suspected early onset sepsis',
      },
    ],
    lineAssociated: false,
    outcome: 'resolved',
    notes: 'Antibiotics stopped after 5 days with negative cultures and improving clinical condition',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(7),
  },
];

// Discharge Checklists
export const DEMO_DISCHARGE_CHECKLISTS: DischargeChecklist[] = [
  {
    id: 'discharge-daisy',
    babyId: 'daisy',
    motherName: 'Rachel Smith',
    fatherName: 'David Smith',
    parentalRelationshipStatus: 'married',
    siblings: [
      { name: 'Oliver Smith', age: 5 },
    ],
    gpDetails: {
      practiceName: 'Riverside Medical Centre',
      gpName: 'Dr. Sarah Williams',
      address: '123 High Street, Manchester, M1 1AB',
      phone: '0161 123 4567',
      registered: true,
    },
    healthVisitor: {
      name: 'Jane Thompson',
      contact: '0161 234 5678',
      informed: false,
    },
    communityReferrals: {
      communityNurse: false,
      healthVisitor: true,
      communityPaediatrician: false,
      earlyInterventionTeam: false,
      physiotherapy: false,
      occupationalTherapy: false,
      speechAndLanguage: false,
      dietitian: false,
    },
    hospitalReferrals: {
      ophthalmology: true,
      ophthalmologyDate: daysAgo(-14),
      audiology: true,
      audiologyDate: daysAgo(-7),
      cardiology: false,
      respiratory: false,
      neurology: false,
    },
    infantServicesRequired: {
      hearingScreening: { required: true, completed: false },
      eyeScreening: { required: true, completed: false },
      oxygenTeam: { required: false, arranged: false },
      nasogastricFeeding: { required: false, parentsTrained: false },
      medicationAdministration: { required: true, parentsTrained: false },
      apnoeaMonitor: { required: false, arranged: false },
    },
    parentEducation: {
      basicBabyCare: true,
      feedingSupport: true,
      medicationAdministration: false,
      cpRTraining: false,
      recognisingIllness: true,
      safeSleeping: true,
      carSeatSafetyCheck: false,
      smokingCessationAdvice: true,
      immunisationDiscussion: true,
    },
    medicationsGoingHome: [
      {
        medication: 'Caffeine Citrate',
        dose: '5mg/kg',
        frequency: 'Once daily',
        duration: '2 weeks',
        prescriptionProvided: false,
      },
      {
        medication: 'Vitamin D',
        dose: '400 units',
        frequency: 'Once daily',
        duration: 'Ongoing',
        prescriptionProvided: false,
      },
    ],
    equipmentGoingHome: {
      oxygenConcentrator: false,
      apnoeaMonitor: false,
      feedingPump: false,
      nasogastricTubes: false,
      suction: false,
    },
    followUpAppointments: [
      {
        service: 'Neonatal Outpatient Clinic',
        date: daysAgo(-21),
        location: 'St Mary\'s Hospital',
        booked: false,
      },
      {
        service: 'Ophthalmology',
        date: daysAgo(-14),
        location: 'Eye Department',
        booked: false,
      },
    ],
    dischargeSummary: {
      completed: false,
      sentToGP: false,
      sentToHealthVisitor: false,
      copyToParents: false,
    },
    redBookCompleted: false,
    redBookGivenToParents: false,
    plannedDischargeDate: daysAgo(-5),
    dischargeDestination: 'home',
    transportHome: 'own_car',
    carSeatAvailable: true,
    createdAt: daysAgo(3),
    updatedAt: now(),
  },
];

// Daily Weight Charts
export const DEMO_WEIGHT_CHARTS: DailyWeightChart[] = [
  {
    id: 'weight-daisy',
    babyId: 'daisy',
    weights: [
      {
        date: daysAgo(5),
        ageInDays: 0,
        correctedGestationalAge: { weeks: 32, days: 4 },
        weightGrams: 1850,
        weightKg: 1.85,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(4),
        ageInDays: 1,
        correctedGestationalAge: { weeks: 32, days: 5 },
        weightGrams: 1820,
        weightKg: 1.82,
        percentile: 25,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(3),
        ageInDays: 2,
        correctedGestationalAge: { weeks: 32, days: 6 },
        weightGrams: 1810,
        weightKg: 1.81,
        percentile: 25,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(2),
        ageInDays: 3,
        correctedGestationalAge: { weeks: 33, days: 0 },
        weightGrams: 1840,
        weightKg: 1.84,
        percentile: 25,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(1),
        ageInDays: 4,
        correctedGestationalAge: { weeks: 33, days: 1 },
        weightGrams: 1875,
        weightKg: 1.875,
        percentile: 30,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
    ],
    growthAssessment: {
      assessmentDate: daysAgo(1),
      birthWeight: 1850,
      currentWeight: 1875,
      weightGain: 25,
      averageDailyGain: 6.25,
      percentWeightLoss: 2.16,
      backToBirthWeight: true,
      backToBirthWeightDate: daysAgo(2),
      growthVelocity: 'adequate',
      nutritionalConcerns: false,
    },
    chartType: 'Fenton',
    createdAt: daysAgo(5),
    updatedAt: now(),
  },
  {
    id: 'weight-elsa',
    babyId: 'elsa',
    weights: [
      {
        date: daysAgo(12),
        ageInDays: 0,
        correctedGestationalAge: { weeks: 28, days: 2 },
        weightGrams: 1120,
        weightKg: 1.12,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(11),
        ageInDays: 1,
        correctedGestationalAge: { weeks: 28, days: 3 },
        weightGrams: 1090,
        weightKg: 1.09,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(10),
        ageInDays: 2,
        correctedGestationalAge: { weeks: 28, days: 4 },
        weightGrams: 1070,
        weightKg: 1.07,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(9),
        ageInDays: 3,
        correctedGestationalAge: { weeks: 28, days: 5 },
        weightGrams: 1060,
        weightKg: 1.06,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(8),
        ageInDays: 4,
        correctedGestationalAge: { weeks: 28, days: 6 },
        weightGrams: 1065,
        weightKg: 1.065,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(7),
        ageInDays: 5,
        correctedGestationalAge: { weeks: 29, days: 0 },
        weightGrams: 1075,
        weightKg: 1.075,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(6),
        ageInDays: 6,
        correctedGestationalAge: { weeks: 29, days: 1 },
        weightGrams: 1090,
        weightKg: 1.09,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(5),
        ageInDays: 7,
        correctedGestationalAge: { weeks: 29, days: 2 },
        weightGrams: 1105,
        weightKg: 1.105,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(4),
        ageInDays: 8,
        correctedGestationalAge: { weeks: 29, days: 3 },
        weightGrams: 1120,
        weightKg: 1.12,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(3),
        ageInDays: 9,
        correctedGestationalAge: { weeks: 29, days: 4 },
        weightGrams: 1138,
        weightKg: 1.138,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(2),
        ageInDays: 10,
        correctedGestationalAge: { weeks: 29, days: 5 },
        weightGrams: 1152,
        weightKg: 1.152,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
      {
        date: daysAgo(1),
        ageInDays: 11,
        correctedGestationalAge: { weeks: 29, days: 6 },
        weightGrams: 1165,
        weightKg: 1.165,
        measurementMethod: 'scale',
        measuredBy: 'sarah-nurse',
      },
    ],
    growthAssessment: {
      assessmentDate: daysAgo(1),
      birthWeight: 1120,
      currentWeight: 1165,
      weightGain: 45,
      averageDailyGain: 4.09,
      percentWeightLoss: 5.36,
      backToBirthWeight: true,
      backToBirthWeightDate: daysAgo(4),
      growthVelocity: 'adequate',
      nutritionalConcerns: false,
      nutritionalPlan: 'Continue feeding advancement, monitor tolerance',
    },
    chartType: 'Fenton',
    createdAt: daysAgo(12),
    updatedAt: now(),
  },
];

// Admission Assessments
export const DEMO_ADMISSION_ASSESSMENTS: AdmissionAssessment[] = [
  {
    id: 'admission-daisy',
    babyId: 'daisy',
    admissionDateTime: daysAgo(5),
    timeOfBirth: daysAgo(5),
    reasonForAdmission: 'Prematurity at 32+4 weeks gestation',
    admissionDiagnoses: ['Prematurity', 'Respiratory distress syndrome', 'Rule out sepsis'],
    birthDetails: {
      birthWeight: 1850,
      gestation: { weeks: 32, days: 4 },
      deliveryMethod: 'emergency_CS',
      apgarScores: { oneMin: 7, fiveMin: 9, tenMin: 9 },
      resuscitation: true,
      resuscitationDetails: 'Facial oxygen and stimulation for 2 minutes',
    },
    maternalHistory: {
      age: 34,
      parity: 'Para 1+1',
      pregnancyComplications: ['Gestational diabetes'],
      groupBStrep: false,
      membranesRuptured: '2 hours before delivery',
    },
    initialVitals: {
      heartRate: 148,
      respiratoryRate: 58,
      bloodPressure: { systolic: 52, diastolic: 32 },
      temperature: 36.5,
      bloodGlucose: 3.8,
      oxygenSaturation: 94,
    },
    measurements: {
      weight: 1850,
      headCircumference: 29.5,
      length: 42,
    },
    vitaminK: {
      given: true,
      dose: 1,
      route: 'IM',
      dateTime: daysAgo(5),
    },
    monitoring: {
      cardiacMonitoring: true,
      saturationMonitoring: true,
      bloodGlucoseMonitoring: true,
    },
    feedingPlan: {
      chosenMethod: 'tube',
      motherIntention: 'breast',
      colostrum: true,
    },
    screening: {
      nbsScreeningDate: daysAgo(2),
      preDischargeScreeningRequired: true,
    },
    welcomePackGiven: true,
    parentDetails: {
      name: 'Rachel Smith',
      contactNumber: '07700 900123',
      relationship: 'Mother',
    },
    riskAssessments: {
      infectionRisk: 'moderate',
      safeguardingConcerns: false,
      socialServicesinvolved: false,
    },
    initialPlan: 'Admit to NICU. Monitor respiratory status. Start feeding when stable. Blood cultures and antibiotics if indicated.',
    admittedBy: 'james-doctor',
    assessedBy: 'emma-consultant',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: 'admission-elsa',
    babyId: 'elsa',
    admissionDateTime: daysAgo(12),
    timeOfBirth: daysAgo(12),
    reasonForAdmission: 'Extreme prematurity at 28+2 weeks gestation, twin pregnancy',
    admissionDiagnoses: ['Extreme prematurity', 'RDS requiring ventilation', 'Rule out sepsis', 'Twin-twin transfusion syndrome'],
    birthDetails: {
      birthWeight: 1120,
      gestation: { weeks: 28, days: 2 },
      deliveryMethod: 'emergency_CS',
      apgarScores: { oneMin: 4, fiveMin: 7, tenMin: 8 },
      resuscitation: true,
      resuscitationDetails: 'Intubation and ventilation for 5 minutes, surfactant given',
    },
    maternalHistory: {
      age: 36,
      parity: 'Para 0+0',
      pregnancyComplications: ['Twin-twin transfusion syndrome', 'Preeclampsia'],
      medications: ['Labetalol'],
      groupBStrep: false,
      membranesRuptured: 'At delivery',
    },
    initialVitals: {
      heartRate: 165,
      respiratoryRate: 0,
      bloodPressure: { systolic: 38, diastolic: 22 },
      temperature: 35.8,
      bloodGlucose: 2.8,
      oxygenSaturation: 85,
    },
    measurements: {
      weight: 1120,
      headCircumference: 25.5,
      length: 36,
    },
    vitaminK: {
      given: true,
      dose: 0.5,
      route: 'IM',
      dateTime: daysAgo(12),
    },
    monitoring: {
      cardiacMonitoring: true,
      saturationMonitoring: true,
      bloodGlucoseMonitoring: true,
    },
    feedingPlan: {
      chosenMethod: 'TPN',
      motherIntention: 'breast',
    },
    screening: {
      preDischargeScreeningRequired: true,
    },
    welcomePackGiven: true,
    parentDetails: {
      name: 'Sophie Brown',
      contactNumber: '07700 900456',
      relationship: 'Mother',
    },
    riskAssessments: {
      infectionRisk: 'high',
      safeguardingConcerns: false,
      socialServicesinvolved: false,
    },
    initialPlan: 'Admit to NICU. Continue ventilation. Start TPN. Blood cultures and antibiotics. Monitor for complications of prematurity.',
    admittedBy: 'emma-consultant',
    assessedBy: 'emma-consultant',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
];

// Sample Collections
export const DEMO_SAMPLES: SampleCollectionMetadata[] = [
  {
    id: 'sample-daisy-blood-culture',
    babyId: 'daisy',
    sampleType: 'blood_culture',
    collectionDateTime: daysAgo(5),
    collectedBy: 'sarah-nurse',
    collectionMethod: 'Peripheral venepuncture',
    barcodeNumber: 'BC123456',
    volume: 0.5,
    clinicalIndication: 'Rule out early onset sepsis',
    requestingDoctor: 'james-doctor',
    laboratory: 'microbiology',
    testsRequested: ['Blood culture', 'Sensitivity'],
    sentToLabDateTime: daysAgo(5),
    sentBy: 'sarah-nurse',
    resultsReceived: true,
    resultsDateTime: daysAgo(3),
    resultsLocation: 'EPR system',
    criticalResult: false,
    notes: 'No growth after 48 hours',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
  },
  {
    id: 'sample-elsa-blood-culture',
    babyId: 'elsa',
    sampleType: 'blood_culture',
    collectionDateTime: daysAgo(12),
    collectedBy: 'sarah-nurse',
    collectionMethod: 'UAC',
    barcodeNumber: 'BC234567',
    volume: 0.5,
    clinicalIndication: 'Rule out early onset sepsis',
    requestingDoctor: 'emma-consultant',
    laboratory: 'microbiology',
    testsRequested: ['Blood culture', 'Sensitivity'],
    sentToLabDateTime: daysAgo(12),
    sentBy: 'sarah-nurse',
    resultsReceived: true,
    resultsDateTime: daysAgo(10),
    resultsLocation: 'EPR system',
    criticalResult: false,
    notes: 'No growth after 48 hours',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(10),
  },
];

// Enhanced Care Plans (Ward Round-Driven)
export const DEMO_ENHANCED_CARE_PLANS: EnhancedCarePlan[] = [
  // Daisy's Enhanced Care Plan (version 2 - feeding plan)
  {
    id: 'enhanced-care-plan-daisy-v2',
    babyId: 'daisy',
    version: 2,
    wardRoundDate: daysAgo(1),
    supersedes: 'enhanced-care-plan-daisy-v1',
    category: 'comprehensive',
    title: 'Comprehensive Care Plan - Daisy',
    description: 'Feeding advancement, routine observations, and developmental care for 32+4 week infant',
    prescribedBy: 'emma-consultant',
    approvedBy: 'emma-consultant',
    reviewDate: now(),
    status: 'active',
    effectiveFrom: daysAgo(1),
    feedingPlan: {
      frequency: 3, // 3-hourly
      volumePerFeed: 40, // ml
      feedType: 'fortified_EBM',
      route: 'NG_tube',
      fortification: {
        type: 'Nutriprem Breast Milk Fortifier',
        scoopsPer100ml: 2,
      },
      specialInstructions: ['Check aspirates before each feed', 'Advance by 5ml if well tolerated'],
      aspirateBeforeFeed: true,
      minimumInterval: 2.5,
    },
    medicationPlan: {
      prescriptionIds: ['caffeine-daisy', 'vitamin-d-daisy'],
      administrationGuidelines: 'Caffeine can be given in feeds. Vitamin D to be given separately.',
    },
    observationPlan: {
      frequency: '4-hourly',
      parameters: {
        weight: { frequency: 'daily', time: '08:00' },
        temperature: true,
        heartRate: true,
        respiratoryRate: true,
        oxygenSaturation: true,
        bloodPressure: false,
      },
      escalationCriteria: [
        { parameter: 'Temperature', threshold: '<36.5°C or >37.5°C', action: 'Inform medical team' },
        { parameter: 'Heart Rate', threshold: '<100 or >180 bpm', action: 'Escalate immediately' },
      ],
    },
    developmentalPlan: {
      kangarooCare: true,
      minimumHandling: true,
      clusteredCare: true,
      lightReduction: true,
      noiseReduction: true,
    },
    additionalInstructions: [
      'Encourage parental involvement with feeds',
      'Monitor for apnoeas and bradycardias',
      'Consider transitioning to oral feeds when ready',
    ],
    changeHistory: [
      {
        date: daysAgo(1),
        changedBy: 'emma-consultant',
        changes: 'Increased feed volume from 35ml to 40ml',
        reason: 'Good tolerance, appropriate weight gain',
      },
    ],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    createdBy: 'emma-consultant',
  },
  // Elsa's Enhanced Care Plan (version 3 - comprehensive)
  {
    id: 'enhanced-care-plan-elsa-v3',
    babyId: 'elsa',
    version: 3,
    wardRoundDate: daysAgo(1),
    supersedes: 'enhanced-care-plan-elsa-v2',
    category: 'comprehensive',
    title: 'Comprehensive Care Plan - Elsa',
    description: 'Ventilation weaning, cautious feed advancement, line care, and intensive monitoring for 28+2 week infant',
    prescribedBy: 'emma-consultant',
    approvedBy: 'emma-consultant',
    reviewDate: now(),
    status: 'active',
    effectiveFrom: daysAgo(1),
    feedingPlan: {
      frequency: 3,
      volumePerFeed: 25,
      feedType: 'fortified_EBM',
      route: 'NG_tube',
      fortification: {
        type: 'Nutriprem Breast Milk Fortifier',
        scoopsPer100ml: 2,
      },
      specialInstructions: ['Minimal feeds for gut priming', 'Hold feeds if aspirates >50% volume', 'Monitor for NEC signs'],
      aspirateBeforeFeed: true,
      minimumInterval: 3,
    },
    medicationPlan: {
      prescriptionIds: ['caffeine-elsa', 'vitamin-d-elsa', 'benzylpenicillin-elsa', 'gentamicin-elsa'],
      administrationGuidelines: 'IV antibiotics via UAC. Caffeine can be given in feeds. Vitamin D separate.',
    },
    observationPlan: {
      frequency: '2-hourly',
      parameters: {
        weight: { frequency: 'daily', time: '08:00' },
        temperature: true,
        heartRate: true,
        respiratoryRate: true,
        oxygenSaturation: true,
        bloodPressure: true,
      },
      escalationCriteria: [
        { parameter: 'Temperature', threshold: '<36.2°C or >37.8°C', action: 'Immediate medical review' },
        { parameter: 'Oxygen Saturation', threshold: '<85%', action: 'Escalate immediately' },
        { parameter: 'Blood Pressure', threshold: 'MAP <30 mmHg', action: 'Urgent medical review' },
      ],
    },
    respiratoryPlan: {
      mode: 'SIMV',
      settings: {
        fiO2Target: 30,
        peep: 6,
        pip: 18,
        rate: 40,
      },
      weaningProtocol: 'Reduce rate by 5 if pH >7.35 and pCO2 <6.5 kPa',
      assessmentFrequency: '4-hourly blood gas',
    },
    proceduralPlan: {
      lineCare: {
        lineIds: ['uac-elsa', 'uvc-elsa'],
        flushFrequency: 4, // 4-hourly flushes
        dressingChangeFrequency: 7, // Weekly
      },
      tubeCare: {
        tubeIds: ['ng-tube-elsa'],
        positionCheckFrequency: 6, // 6-hourly
      },
      positionChanges: {
        frequency: 3, // 3-hourly
        positions: ['prone', 'supine', 'left lateral', 'right lateral'],
      },
      skinAssessments: {
        frequency: 6, // 6-hourly
      },
    },
    developmentalPlan: {
      kangarooCare: false, // Too unstable currently
      minimumHandling: true,
      clusteredCare: true,
      lightReduction: true,
      noiseReduction: true,
    },
    additionalInstructions: [
      'Strict infection control',
      'Monitor for signs of IVH - cranial USS pending',
      'Daily review of respiratory support',
      'Consider surfactant if deterioration',
      'Blood cultures if temperature instability',
    ],
    changeHistory: [
      {
        date: daysAgo(1),
        changedBy: 'emma-consultant',
        changes: 'Reduced ventilator rate from 45 to 40. Increased feed volume from 20ml to 25ml',
        reason: 'Improving respiratory status. Good feed tolerance',
      },
    ],
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    createdBy: 'emma-consultant',
  },
];

// Generate Nursing Tasks (24 hours ahead from now)
const generateTasksForBaby = (babyId: string): NursingTask[] => {
  const carePlan = DEMO_ENHANCED_CARE_PLANS.find((cp) => cp.babyId === babyId && cp.status === 'active');
  if (!carePlan) return [];

  const prescriptions = DEMO_PRESCRIPTIONS.filter((p) => p.babyId === babyId && p.status === 'approved');

  return generateAllTasks(carePlan, prescriptions, now(), 24);
};

// Generate tasks for both babies
let allGeneratedTasks = [
  ...generateTasksForBaby('daisy'),
  ...generateTasksForBaby('elsa'),
];

// Mark some tasks as completed (simulate past completions)
allGeneratedTasks = allGeneratedTasks.map((task, index) => {
  const scheduledMillis = task.scheduledDateTime.toMillis();
  const nowMillis = now().toMillis();

  // Mark tasks from more than 2 hours ago as completed
  if (scheduledMillis < nowMillis - 2 * 60 * 60 * 1000) {
    return {
      ...task,
      status: 'completed' as const,
      completedAt: Timestamp.fromMillis(scheduledMillis + 10 * 60 * 1000), // Completed 10 min after scheduled
      completedBy: 'sarah-nurse',
      completionRecordId: `${task.taskType}-record-${task.id}`,
      completionRecordType: task.taskType === 'feeding' ? 'FeedingRecord' as const :
                           task.taskType === 'medication' ? 'MedicationAdministration' as const :
                           task.taskType === 'vital_signs' ? 'VitalSign' as const :
                           'ProcedureRecord' as const,
    };
  }

  // Mark one task as overdue for demo
  if (index === 5 && scheduledMillis < nowMillis) {
    return { ...task, status: 'overdue' as const };
  }

  // Mark tasks within 30 min window as 'due'
  if (scheduledMillis >= nowMillis - 30 * 60 * 1000 && scheduledMillis <= nowMillis) {
    return { ...task, status: 'due' as const };
  }

  return task;
});

export const DEMO_NURSING_TASKS: NursingTask[] = allGeneratedTasks;

// Task Completion Summary (yesterday)
export const DEMO_TASK_COMPLETION_SUMMARIES: TaskCompletionSummary[] = [
  {
    id: 'task-summary-daisy-yesterday',
    babyId: 'daisy',
    date: daysAgo(1),
    shift: 'day',
    totalTasksScheduled: 22,
    tasksCompleted: 21,
    tasksDeferred: 1,
    tasksMissed: 0,
    tasksCancelled: 0,
    variances: [
      {
        taskId: 'feed-daisy-15:00',
        taskType: 'feeding',
        scheduledTime: Timestamp.fromDate(new Date(Date.now() - 24 * 60 * 60 * 1000 + 15 * 60 * 60 * 1000)),
        actualTime: Timestamp.fromDate(new Date(Date.now() - 24 * 60 * 60 * 1000 + 15.5 * 60 * 60 * 1000)),
        varianceMinutes: 30,
        reason: 'Baby sleeping - deferred to allow rest',
      },
    ],
    clinicallySignificantVariances: false,
    escalatedToMedicalTeam: false,
    compiledBy: 'sarah-nurse',
    createdAt: daysAgo(1),
  },
  {
    id: 'task-summary-elsa-yesterday',
    babyId: 'elsa',
    date: daysAgo(1),
    shift: 'day',
    totalTasksScheduled: 35,
    tasksCompleted: 34,
    tasksDeferred: 0,
    tasksMissed: 1,
    tasksCancelled: 0,
    variances: [
      {
        taskId: 'feed-elsa-12:00',
        taskType: 'feeding',
        scheduledTime: Timestamp.fromDate(new Date(Date.now() - 24 * 60 * 60 * 1000 + 12 * 60 * 60 * 1000)),
        reason: 'Feed held due to high aspirates - medical team informed',
      },
    ],
    clinicallySignificantVariances: true,
    escalatedToMedicalTeam: true,
    compiledBy: 'sarah-nurse',
    createdAt: daysAgo(1),
  },
];

// Mock data store
export const mockDataStore = {
  users: DEMO_USERS,
  babies: DEMO_BABIES,
  prescriptions: DEMO_PRESCRIPTIONS,
  medications: DEMO_MEDICATIONS,
  carePlans: DEMO_CARE_PLANS,
  feeds: DEMO_FEEDS,
  vitalSigns: DEMO_VITAL_SIGNS,
  parents: DEMO_PARENTS,
  housing: DEMO_HOUSING,
  consents: DEMO_CONSENTS,
  ivLines: DEMO_IV_LINES,
  ngTubes: DEMO_NG_TUBES,
  bloodGas: DEMO_BLOOD_GAS,
  fluidBalance: DEMO_FLUID_BALANCE,
  twentyFourHrResume: DEMO_24HR_RESUME,
  infections: DEMO_INFECTIONS,
  dischargeChecklists: DEMO_DISCHARGE_CHECKLISTS,
  weightCharts: DEMO_WEIGHT_CHARTS,
  admissionAssessments: DEMO_ADMISSION_ASSESSMENTS,
  samples: DEMO_SAMPLES,
  enhancedCarePlans: DEMO_ENHANCED_CARE_PLANS,
  nursingTasks: DEMO_NURSING_TASKS,
  taskCompletionSummaries: DEMO_TASK_COMPLETION_SUMMARIES,
};
